### ISSUE TITLE
Make activies easier/faster to start

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#120]
The current link to the Activity menu is hidden (at least on mobile, which is the intended platform) and when you're in it, clogged with irrelevant items.

Suggested flow:
-A "Play SmartZoos" link directly on the start page. 

-Once in the Activity menu, make it a first step to choose which location you want activities for. (Skansen, Korkeasaari, Tallin, etc), to remove activities clearly not relevant to the user. (Alternatively, if the user is sent to SmartZoos via eg the Zoo's website, that choice has already been made.) 

-Shrink the space a Activity has in the list. Cut unnecessary info. (There should be guidelines for how long the description should be. Eg, Max amount of character to force/encourage a quick and concise text. It's not reasonable to have a description cover a whole screen length)

-Make the Play button bigger. Users more often seem to click the link. Is the page where the Activity info in shown even necessary for the end user? It shows the same stuff as the Start box

Visual will be added.

**Comment by PatriciaMoller** [comment]
![startpage with start link](https://cloud.githubusercontent.com/assets/26867575/26625709/375a82c2-45f5-11e7-8b3d-8935efdf5edc.png)

A large, hard-to-miss button on the front page. To cut down the amount of menu-digging the player has to do.

![startpage with zoo links](https://cloud.githubusercontent.com/assets/26867575/26625250/d38b6082-45f3-11e7-8b68-1a8e5ceb1a47.png)

Have the player chose their location, in order to filter the Activities and only show results relevant to them.

![activitylist_improvements](https://cloud.githubusercontent.com/assets/26867575/26625254/d60a6470-45f3-11e7-9b75-bda0cd95d80c.png)

A modified version of the current Activity list. Irrelevant info has been cut and the play button much bigger

**Comment by pjotrsavitski** [comment]
@PatriciaMoller 

I like the idea, but have a few questions.

1. Clicking on the initial button display three new elements instead of it, pressing any of those takes the user into the page with activity listing?
2. Could we reuse the current activity listing page and just make sure that front page redirects with some kind of parameter, then that is just silently used as a filtering mechanics? This could also be integrated into the search we currently have there.
3. Could the elements/buttons for Zoos be just placed one after another, as a listing? Or we could just use the icons for the zoos (images we already have at the bottom of the page)?
4. The listing view for single activity has to be the same on both mobile and non-mobile screens (we will be determining that by screen size, not the device type)? We only anticipate games to be played on handheld devices, so we could only focus on what is best for those.

If we keep it small and simple, then we could have the change done before the next round of usage next week. That should give us an immediate feedback.

**Comment by PatriciaMoller** [comment]
1. I noticed that I hadn't edited the Url. Pressing the "Play" button can lead to the activity page. I'm not sure which way is the best on a technical level, but taking the player to another page (the Activity or making a new page for "Choose location") would act as a clear Starting Point.
2. Redirecting with a filter parameter sound like a smooth way to do it.
3. A list would be okay. I'd prefer a 2-column grid, but that would mostly make sense if there are 4 or more options are available. I think that makes more use of the screen space. Yes to having logos.
4. I don't really understand the question. The screenshot is based on the mobile layout on our phones.
5. "Load More" seems to be a bit more standard for mobile site, and not as finicky as page numbers and next/back buttons. I support that

The testing for that can not be done by me or Petronella, as we will not be part of the project after this week.

**Comment by kaimikael** [comment]
I guess we could even choose the play site based on the players position (though that might require some way of indicating that one actually wants to start a game for a different zoo, if that for some reason would be useful, I think we had some potential scenarios for that).
Further, I think the "What is SmartZoos" could be dropped from the front page – add an "i" icon or something for the credits.
