### ISSUE TITLE
Correct/Incorrect/Complete question images

### ISSUE THREAD

**Issue by Pnella** [SmartZoos/Toolset#140]
@PatriciaMoller and I have been doing some talking, I've been doing some illustrations for this which she will use to explain what this is about and what it could look like.

**Comment by PatriciaMoller** [comment]
The idea was to have these after a question has been answered correctly/incorrectly, to make the event livelier. 

![correct](https://user-images.githubusercontent.com/26867575/30956863-d38af720-a438-11e7-926d-635ff0c3097a.gif) ![wrong](https://user-images.githubusercontent.com/26867575/30957260-0a562972-a43a-11e7-82e6-5b52f231182d.gif)

It hit me that using text maybe isn't a good idea, as they would have to be localized. Maybe using  fancier version of the the symbols used on the map would be better from that perspective.

Maybe they could be further animated the Spritesheet+JSON method mention [here](https://github.com/SmartZoos/Toolset/issues/138#issuecomment-332765123) could be applicable 

Illustrations found here: [Wrong](https://drive.google.com/open?id=0B7ghDGIir49XX1pITFhaak9ucjg), [Correct](https://drive.google.com/open?id=0B7ghDGIir49XOEozV1pFY20yS0k)

**Comment by kaimikael** [comment]
Oh, I love those!

**Comment by PatriciaMoller** [comment]
En extension of the Correct gif:
![correctv3](https://user-images.githubusercontent.com/26867575/30960161-7dbfc794-a442-11e7-8478-0f8c76257388.gif)

The "bubble" shrinks and goes to the progress bar. When it "hits", the number goes up

**Comment by pjotrsavitski** [comment]
Can not comment about the animation technique to be used (have to check out the sprite approach first).

We should probably not use texts within the images. We could create a complicated elements and animate those, but then we are no longer talking about sprite animations (that would become too complicated).

We should also keep to one approach, instead of rushing with too many visuals. By that I mean: we either have those (or something similar) or jumping question markers. The visuals should not be too overwhelming.

**Comment by PatriciaMoller** [comment]
The text used when I did this mockup is an image of text (so, a sprite). Do you mean text, as in actual strings of text, shouldn't be used? 

Maybe having both, in their current forms, would be overwhelming as you say. 
I apologize that I rush and I throw so many different workflow suggestions. I want to find a way so I can make animations and visual assets as "ready-to-use" as possible and figure out what kind of assets would be needed from my end. Web-based platforms like this is a bit of a new territory, as I have mostly worked in game engines.

**Comment by pjotrsavitski** [comment]
Yes, if we just want to stick to images/sprites or anything else, then we should keep away from texts. We could use the complex HTML elements and animate those instead (this would allow translating). But that would make using sprite animations that you have liked impossible.

Not a big deal. It takes time to try out the visual things and it sometimes take a long time to understand how something could be applied (especially when one uses other libraries or frameworks; Google Maps API is one example, it does not really let you access the DOM nodes, but wants you to use the Marker object and make manipulations through it, but that does not have all the animations we would need; this is why it is easier to just use some animated images because the API to make changes exists).

**Comment by PatriciaMoller** [comment]
![correctv2](https://user-images.githubusercontent.com/26867575/32332135-ff38ea22-bfe4-11e7-9522-7f347df09c09.gif)

One correct, Multiple Correct and Match pairs should these, as they do have correct answers.
Information doesn't need it, since it's just a box of text to be read.
Photo and Embedded feel trickier as they don't necessarily have to be questions. 
Freeform as well, as there is no way to know if they're actually correct when. Maybe having a "Submitted!" image for those three?

**Comment by pjotrsavitski** [comment]
Yes, that is one possibility. We should probably differentiate between those that automatically checked and those that are not (if that is important enough).

**Comment by PatriciaMoller** [comment]
Not super important maybe, but I think it could feel rather strange if someone wrote gibberish in a freeform and got rewarded with a "Correct!".

Having different images could seem inconsistent to some, but it would also give more correct and representing feedback for what they did.

**Comment by pjotrsavitski** [comment]
Agree with that in full. It would seem strange indeed.

**Comment by PatriciaMoller** [comment]
Suggested CSS-animations:

Correct: In - bounceInUp . Out - bounceOut.
Wrong: In - bounceInDown. Out - bounceOutDown.
Submitted: In - bounceInRight. Out - bounceOutLeft.

"Submitted" image found [here](https://drive.google.com/file/d/1Tl6sMSJYW8HbXA2K90s15chjFoACduFm/view?usp=sharing)

**Comment by PatriciaMoller** [comment]
Updated[ Correct](https://drive.google.com/open?id=1X7rCo-DpWNbByUn8RQ1esVgTwiKoLaXP), [Incorrect](https://drive.google.com/open?id=1ce4upg2nLWJPi3N3UTCaoot-n1EpIKQs) and [Submitted](https://drive.google.com/open?id=1qLGzHNiYyo_6kx-dfQHhx5Iz3vY6DX_7) images

**Comment by kaimikael** [comment]
Is this anything that we will implement in the released version?  I have received requests from Korkeasaari as well for fancier feedback when answering questions.

**Comment by pjotrsavitski** [comment]
Will see how things go. If I manage to get visuals running without issues and fast enough. Then a more or less generic solution would allow that to be implemented without too many complications.
