### ISSUE TITLE
Adding activity items to activity

### ISSUE THREAD

**Issue by tammets** [SmartZoos/Toolset#47]
User is able to add activity items to activity using search and filter tool.

![screen shot 2017-02-19 at 10 57 32](https://cloud.githubusercontent.com/assets/380007/23100828/7b3d590e-f692-11e6-8f9a-cb99ab664e25.png)

**Comment by tammets** [comment]
Might also need some preview functionality for the item.

**Comment by pjotrsavitski** [comment]
Will need to discuss that a bit before implementing. This does not seem to be part of the create/update view of activity.

Once we get icons for types, then showing an icon instead of the text (at least within the listing)  should be beneficial (especially on mobile devices).

Activity already has the fields for Zoo, Language and Difficulty Level (these values could be reused, if this one would be part of the normal create/update flow).
Difficulty Level and Playing Time are not currently part of a single activity, but are the attributes of the Activity itself. That would probably need to change.
We currently do not use keywords/tags, but the search could consider both **title** and **description** if needed.

**Comment by pjotrsavitski** [comment]
The implementation is still missing filtering by some fields, but implementing that is impossible until the changes to the structures are made. I'm closing the issue as the functionality is there and working. A new one(s) should be created for making changes required.
